twig:
    default_path: "%kernel.project_dir%/templates"
    globals:
        app_env: "%env(APP_ENV)%"
        app_title: "%env(APP_TITLE)%"
        apidaebundle_taches_path: "%env(APIDAEBUNDLE_TACHES_PATH)%"
when@test:
    twig:
        strict_variables: true
